version: '3'
services:
  app:
    build: .
    # image: codepad.online:1.#{Build.BuildId}#
    image: codepad.online:0.1.0
    ports:
      - 5200:80
    networks:
      appnet:
        aliases:
          - codepad.online
networks:
  appnet: {}