# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: codepad/
    # image: codepad.online:1.#{Build.BuildId}#
    image: codepad.online:0.1.4
    ports:
      - 5200:80
    networks:
      appnet:
        aliases:
          - codepad.online

  api:
    build: codepad.api/
    image: codepad.online.api:0.1.3
    ports:
      - 5121:5000 # 5120 is via ssl
    networks:
      appnet:
        aliases:
          - api.codepad.online

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 5110:27017
    volumes:
      - ./mongo-volume:/data/db
    networks:
      appnet:
        aliases:
          - mongo.codepad.online

networks:
  appnet: {}
