apiVersion: v1
kind: Service
metadata:
  labels:
    name: codepad-frontend
  name: codepad-frontend
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: codepad-frontend
  type: ClusterIP