apiVersion: v1
kind: Service
metadata:
  labels:
    name: codepad-api
  name: codepad-api
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: codepad-api
  type: NodePort